add parition subcmd

diff --git a/zbectl b/zbectl
--- a/zbectl
+++ b/zbectl
@@ -130,6 +130,7 @@ unmount_env() {
 }
 
 parent_devices() {
+	# zdb needs a zpool cachefile
 	for device in $(zdb -C $POOL | awk -F\' '/path/{print $2}')
 	do
 		lsblk -pno PKNAME ${device}
@@ -147,6 +148,47 @@ mount_esps() {
 		[[ -d $ESP_MNT ]] || mkdir $ESP_MNT
 		mount /dev/disk/by-partuuid/$ESP_PARTUUID $ESP_MNT
 	done
+}
+partition_device() {
+	local device=$1
+	if [[ $EFI == true ]]
+	then
+		echo "Parttioning device: '$device' for EFI use"
+	else
+		echo "Parttioning device: '$device' for BIOS use"
+	fi
+	if !fdisk -l $device 1>/dev/null
+	then
+		device="/dev/$device"
+		fdisk -l $device 1>/dev/null
+	fi
+	[[ $? ]] || die 3 "device: '$1' not valid"
+	(
+	echo g # new GPT table
+	echo n # BIOS/EFI partition
+	echo 1 # partition number
+	echo   # start at beginning
+	if [[ $EFI == true ]]
+	then
+		echo +200M # size of EFI partition
+		echo t # set type
+		echo 1 # select EFI
+	else
+		echo +2M # size of BIOS partition
+		echo t # set type
+		echo 4 # selct BIOS
+	fi
+	echo n # new zfs partition
+	echo 2 # partition number
+	echo # start directly after first partition
+	echo # fill entire disk
+	echo t # set type
+	echo 2 # select partition
+	echo 48 # select ZFS
+	echo w # write changes
+	) | fdisk $device 1>/dev/null
+
+	[[ $? ]] || die 3 "error paritioning device: '$device'"
 }
 update_grub() {
 	ln -sf /dev/null /etc/grub.d/10_linux
@@ -227,20 +269,38 @@ case $subcmd in
 		for ESP in $(mount_esps)
 		do
 			echo "Installing to: $ESP"
-			grub-install --target=x86_64-efi --efi-directory=$ESP --boot-directory=$ESP "${GRUB_ARGS}"
-
+			grub-install --target=x86_64-efi --efi-directory=$ESP --boot-directory=$ESP ${GRUB_ARGS}
+			[[ $? ]] || die 3 "Installing grub failed"
 		done
 	else
-		for device in parent_devices
+		for device in $(parent_devices)
 		do
 			echo "Installing to: $device"
-			grub-install --target=i386-pc "$device" "${GRUB_ARGS}"
+			grub-install --target=i386-pc ${GRUB_ARGS} $device
+			[[ $? ]] || die 3 "Installing grub failed"
 		done
 	fi
 
 	update_grub
 	;;
-
+'partition')
+	devices=${@}
+	for device in ${devices}
+	do
+		partition_device $device
+	done
+	echo "Create your pool over the following devices:"
+	lsblk -fl -o NAME,PARTUUID,FSTYPE ${devices} |
+		awk '/zfs_member/{
+			if ($1 == "NAME") {print $0};
+			if ($2 != "zfs_member") {print $1, $2}
+		}'
+	if [[ $EFI == true ]]
+	then
+		mount_esps
+	fi
+	#echo "Make sure to bootstrap your OS to yourpool/ROOT/yourenvironment"
+	;;
 'update')
 	update_grub
 	;;
