add create from running environment
[source] is now optional for create.

diff --git a/zbectl b/zbectl
--- a/zbectl
+++ b/zbectl
@@ -23,7 +23,6 @@ check_root() {
 		exit 1
 	fi
 }
-
 usage() {
 	echo "zbectl: util for managing boot environments in Arch Linux using ZFS"
 	echo "zbectl list"
@@ -54,7 +53,8 @@ then
 	exit 1
 fi
 
-checkname() {
+checktarget() {
+	# check if name is usable
 	local sane_name=$( echo "${1}" | tr -c -d 'a-zA-Z0-9-_.,' )
 	if [[ "$1" != "$sane_name" ]]
 	then
@@ -63,6 +63,36 @@ checkname() {
 		exit 1
 	fi
 	unset sane_name
+
+	# check if boot environment does already exist
+	if zfs list -H -o name $POOL/ROOT/$TARGET &> /dev/null
+	then
+		echo "ERROR: Boot environment '$TARGET' does already exist"
+		exit 1
+	fi
+}
+createclone() {
+	# create a clone of the $TARGET boot environment
+	FMT=$(date "+%Y-%m-%d-%H:%M:%S")
+	zfs snapshot -r $POOL/ROOT/$SOURCE@zbectl_${FMT}_$TARGET
+	zfs clone $POOL/ROOT/$SOURCE@zbectl_${FMT}_$TARGET $POOL/ROOT/$TARGET
+}
+copykernels() {
+	# copies the kernels to a new boot environment, and updates boot entries
+	mkdir /boot/$TARGET
+	cp /boot/$SOURCE/* /boot/$TARGET/
+	# create new bootentries for all kernels
+	# entries are not generated from scratch to keep kernel options (eg. cryptroot=)
+	for KERNEL in /boot/loader/entries/$SOURCE-*.conf
+	do
+		KERNEL="${KERNEL#/boot/loader/entries/$SOURCE-}"
+		KERNEL="${KERNEL%.conf}"
+		ENTRY="/boot/loader/entries/$TARGET-$KERNEL.conf"
+		cp /boot/loader/entries/$SOURCE-$KERNEL.conf $ENTRY
+		sed -i "s/($SOURCE)/($TARGET)/" "$ENTRY"
+		sed -i "s/\/$SOURCE\//\/$TARGET\//" "$ENTRY"
+		sed -i "s/zfs=$POOL\/ROOT\/$SOURCE/zfs=$POOL\/ROOT\/$TARGET/" "$ENTRY"
+	done
 }
 check_dset_exist() {
 	if ! zfs list -H -o name $POOL/ROOT/$1 &> /dev/null
@@ -117,48 +147,41 @@ then
 	rm -r /boot/$TARGET
 	rm /boot/loader/entries/$TARGET-*.conf
 	
-elif [ $1 == 'create' ] || [ $1 == 'rename' ]
+elif [ $1 == 'create' ]
 then
-	[ $# -ne 3 ] && usage
-	SOURCE=$(basename "${2}")
-	TARGET=$(basename "${3}")
-	check_dset_exist $SOURCE
-	checkname $TARGET
-	if zfs list -H -o name $POOL/ROOT/$TARGET &> /dev/null
+	if [ $# -eq 3 ]
 	then
-		echo "ERROR: Boot environment '$TARGET' does already exist"
-		exit 1
-	fi
-	if [ $1 == 'create' ]
+		TARGET=$(basename "${3}")
+		checktarget $TARGET
+		SOURCE=$(basename "${2}")
+		if zfs list -t filesystem -H $POOL/ROOT/$SOURCE &> /dev/null
+		then
+			createclone
+		else
+			echo "ERROR: Boot environment '$1' does not exist"
+			exit 1
+		fi
+	elif [ $# -eq 2]
 	then
-		FMT=$(date "+%Y-%m-%d-%H:%M:%S")
-		zfs snapshot -r $POOL/ROOT/$SOURCE@zbectl_${FMT}_$TARGET 
-		zfs clone $POOL/ROOT/$SOURCE@zbectl_${FMT}_$TARGET $POOL/ROOT/$TARGET
+		TARGET=$(basename "${2}")
+		checktarget $TARGET
+		SOURCE=$(basename "$ROOTFS")
+		createclone
 	else
-
-		zfs rename $POOL/ROOT/$SOURCE $POOL/ROOT/$TARGET
+		usage
 	fi
-	# update /boot
-	mkdir /boot/$TARGET
-	cp /boot/$SOURCE/* /boot/$TARGET/
+	copykernels
 
-	# creates new bootentries for all kernels
-	# entries are not generated from scratch to keep kernel options (eg. cryptroot=)
-	for KERNEL in /boot/loader/entries/$SOURCE-*.conf
-	do
-		KERNEL="${KERNEL#/boot/loader/entries/$SOURCE-}"
-		KERNEL="${KERNEL%.conf}"
-		ENTRY="/boot/loader/entries/$TARGET-$KERNEL.conf"
-		cp /boot/loader/entries/$SOURCE-$KERNEL.conf $ENTRY
-		sed -i "s/($SOURCE)/($TARGET)/" "$ENTRY"
-		sed -i "s/\/$SOURCE\//\/$TARGET\//" "$ENTRY"
-		sed -i "s/zfs=$POOL\/ROOT\/$SOURCE/zfs=$POOL\/ROOT\/$TARGET/" "$ENTRY"
-	done
-	if [ $1 == 'rename' ]
-	then
-		rm /boot/loader/entries/$SOURCE-*.conf
-		rm -r /boot/$SOURCE 
-	fi
+elif [ $1 == 'rename' ]
+then
+	SOURCE=$(basename "${2}")
+	check_dset_exist $SOURCE
+	TARGET=$(basename "${3}")
+	checktarget $TARGET
+	zfs rename $POOL/ROOT/$SOURCE $POOL/ROOT/$TARGET
+	copykernels
+	rm /boot/loader/entries/$SOURCE-*.conf
+	rm -r /boot/$SOURCE 
 
 elif [ $1 == 'activate' ]
 then
